whitelist_rules:
  - attributes
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - control_statement
  - empty_count
  - fatal_error_message
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - identifier_name
  - implicit_getter
  - implicitly_unwrapped_optional
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - line_length
  - mark
  - multiline_arguments
  - multiline_parameters
  - opening_brace
  - operator_usage_whitespace
  - private_outlet
  - private_unit_test
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - unused_import
  - vertical_whitespace
  - void_return
  - weak_delegate
  - yoda_condition

line_length:
  warning: 120
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 400
  error: 800

function_body_length:
  warning: 40
  error: 60

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 200
  error: 400

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40

excluded:
  - Carthage
  - Pods
  - Vendor
  - Resources

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5
